# Generated by Django 4.2.1 on 2023-05-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0003_alter_user_gender_alter_userpreference_drink_and_more"),
        ("events", "0007_alter_partylocation_options_party_is_closed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(null=True, verbose_name="Сумма"),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.party",
                        verbose_name="Вечеринка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платежи пользователей",
                "verbose_name_plural": "Платежи пользователей",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="CreatorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                ("amount", models.SmallIntegerField(null=True, verbose_name="Сумма")),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.creator",
                        verbose_name="Организатор",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.party",
                        verbose_name="Вечеринка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платежи организаторов",
                "verbose_name_plural": "Платежи организаторов",
                "ordering": ["-datetime"],
            },
        ),
    ]
