# Generated by Django 4.2.1 on 2023-05-18 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "members_amount",
                    models.PositiveSmallIntegerField(
                        verbose_name="Максимальное количество участников"
                    ),
                ),
                ("date", models.DateField(default=datetime.date(2023, 5, 21))),
                ("time", models.TimeField(default="20:00:00")),
                (
                    "age_group",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "preferred_gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "мужчина"), (2, "женщина")],
                        default=None,
                        null=True,
                        verbose_name="Предпочтительный гендер",
                    ),
                ),
                (
                    "music_genre",
                    models.IntegerField(
                        choices=[(1, "рок"), (2, "поп"), (3, "хип-хоп"), (4, "метал")],
                        default=None,
                        null=True,
                        verbose_name="Жанр музыки",
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(default=0, verbose_name="Бюджет"),
                ),
            ],
            options={
                "verbose_name": "Мероприятия",
                "verbose_name_plural": "Мероприятия",
                "db_table": "events_parties",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
