# Generated by Django 4.2.1 on 2023-05-22 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "members_amount",
                    models.PositiveSmallIntegerField(
                        verbose_name="Максимальное количество участников"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date(2023, 5, 25), verbose_name="Дата"
                    ),
                ),
                ("time", models.TimeField(default="20:00:00", verbose_name="Время")),
                (
                    "preferred_gender",
                    models.CharField(
                        blank=True,
                        choices=[("мужчина", "мужчина"), ("женщина", "женщина")],
                        default=None,
                        null=True,
                        verbose_name="Предпочтительный гендер",
                    ),
                ),
                (
                    "music_genre",
                    models.CharField(
                        choices=[
                            ("рок", "рок"),
                            ("поп", "поп"),
                            ("хип-хоп", "хип-хоп"),
                            ("метал", "метал"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="Жанр музыки",
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(default=0, verbose_name="Бюджет"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Набор закрыт"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Мероприятия",
                "verbose_name_plural": "Мероприятия",
                "db_table": "events_parties",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="PartyLocation",
            fields=[
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="events.party",
                        verbose_name="Вечеринка",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Локации",
                "verbose_name_plural": "Локации",
                "ordering": ["district"],
            },
        ),
    ]
