# Generated by Django 4.2.1 on 2023-05-22 10:16

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.agegroup",
                verbose_name="Возрастная группа",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.creator",
                verbose_name="Организатор",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="subculture",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.subculture",
                verbose_name="Субкультура",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="users",
            field=models.ManyToManyField(to="main.user", verbose_name="Участники"),
        ),
        migrations.AddField(
            model_name="partylocation",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.district",
                verbose_name="Район",
            ),
        ),
    ]
