# Generated by Django 4.2.1 on 2023-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="music_genre",
            field=models.CharField(
                choices=[
                    ("рок", "рок"),
                    ("поп", "поп"),
                    ("хип-хоп", "хип-хоп"),
                    ("метал", "метал"),
                ],
                default=None,
                null=True,
                verbose_name="Жанр музыки",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="preferred_gender",
            field=models.CharField(
                blank=True,
                choices=[("мужчина", "мужчина"), ("женщина", "женщина")],
                default=None,
                null=True,
                verbose_name="Предпочтительный гендер",
            ),
        ),
    ]
