# Generated by Django 4.2.1 on 2023-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_age_group"),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="users",
            field=models.ManyToManyField(
                blank=True, to="main.user", verbose_name="Участники"
            ),
        ),
    ]
