# Generated by Django 4.2.1 on 2023-05-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_gender_alter_userpreference_drink_and_more"),
        ("events", "0003_alter_party_music_genre_alter_party_preferred_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.agegroup",
            ),
        ),
    ]
