# Generated by Django 4.2.1 on 2023-05-18 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_gender_alter_userpreference_drink_and_more"),
        ("events", "0005_alter_party_age_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.agegroup",
                verbose_name="Возрастная группа",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 5, 21), verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="time",
            field=models.TimeField(default="20:00:00", verbose_name="Время"),
        ),
        migrations.CreateModel(
            name="PartyLocation",
            fields=[
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="events.party",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.district"
                    ),
                ),
            ],
        ),
    ]
