# Generated by Django 4.2.1 on 2023-05-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_gender_alter_userpreference_drink_and_more"),
        ("events", "0006_alter_party_age_group_alter_party_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partylocation",
            options={
                "ordering": ["district"],
                "verbose_name": "Локации",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.AddField(
            model_name="party",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Набор закрыт"),
        ),
        migrations.AddField(
            model_name="party",
            name="users",
            field=models.ManyToManyField(to="main.user"),
        ),
        migrations.AlterField(
            model_name="partylocation",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="partylocation",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.district",
                verbose_name="Район",
            ),
        ),
        migrations.AlterField(
            model_name="partylocation",
            name="party",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                serialize=False,
                to="events.party",
                verbose_name="Вечеринка",
            ),
        ),
    ]
