# Generated by Django 4.2.1 on 2023-05-19 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_userpreference_subculture_user_subculture"),
        ("events", "0007_alter_partylocation_options_party_is_closed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 5, 22), verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="users",
            field=models.ManyToManyField(to="main.user", verbose_name="Участники"),
        ),
    ]
