# Generated by Django 4.2.1 on 2023-05-22 10:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("молодняк", "молодняк"),
                            ("подрастающие", "подрастающие"),
                            ("почти 30", "почти 30"),
                            ("потрачено", "потрачено"),
                            ("финишная прямая", "финишная прямая"),
                        ],
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "ages_range",
                    models.CharField(
                        choices=[
                            ("18-21", "18-21"),
                            ("22-25", "22-25"),
                            ("25-29", "25-29"),
                            ("30-34", "30-34"),
                            ("35-40", "35-40"),
                        ],
                        max_length=5,
                        unique=True,
                        verbose_name="Границы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возрастные группы",
                "verbose_name_plural": "Возрастные группы",
                "ordering": ["ages_range"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "city",
                    models.CharField(
                        default=None, max_length=50, null=True, verbose_name="Город"
                    ),
                ),
            ],
            options={
                "verbose_name": "Районы",
                "verbose_name_plural": "Районы",
                "ordering": ["city"],
            },
        ),
        migrations.CreateModel(
            name="SubCulture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Субкультуры",
                "verbose_name_plural": "Субкультуры",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        default=None, max_length=50, null=True, verbose_name="Никнейм"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "last_callback",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("мужчина", "мужчина"), ("женщина", "женщина")],
                        default=None,
                        verbose_name="Гендер",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "age_group",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.agegroup",
                        verbose_name="Возрастная группа",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.district",
                        verbose_name="Район",
                    ),
                ),
                (
                    "subculture",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.subculture",
                        verbose_name="Субкультура",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователи",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="main.user",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "music_genre",
                    models.CharField(
                        choices=[
                            ("рок", "рок"),
                            ("поп", "поп"),
                            ("хип-хоп", "хип-хоп"),
                            ("метал", "метал"),
                        ],
                        verbose_name="Жанр музыки",
                    ),
                ),
                (
                    "drink",
                    models.CharField(
                        choices=[
                            ("водка", "водка"),
                            ("ликёр", "ликёр"),
                            ("ром", "ром"),
                            ("виски", "виски"),
                            ("пиво", "пиво"),
                        ],
                        verbose_name="Напиток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предпочтения",
                "verbose_name_plural": "Предпочтения",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="val from 0 to 10",
                        null=True,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "requisites_info",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Реквизиты"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организаторы",
                "verbose_name_plural": "Организаторы",
                "ordering": ["user"],
            },
        ),
    ]
