# Generated by Django 4.2.1 on 2023-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_userpreference_id_alter_userpreference_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("мужчина", "мужчина"), ("женщина", "женщина")],
                default=None,
                verbose_name="Гендер",
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="drink",
            field=models.CharField(
                choices=[
                    ("водка", "водка"),
                    ("ликёр", "ликёр"),
                    ("ром", "ром"),
                    ("виски", "виски"),
                    ("пиво", "пиво"),
                ],
                verbose_name="Напиток",
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="music_genre",
            field=models.CharField(
                choices=[
                    ("рок", "рок"),
                    ("поп", "поп"),
                    ("хип-хоп", "хип-хоп"),
                    ("метал", "метал"),
                ],
                verbose_name="Жанр музыки",
            ),
        ),
    ]
