# Generated by Django 4.2.1 on 2023-05-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_gender_alter_userpreference_drink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="subculture",
        ),
        migrations.AddField(
            model_name="user",
            name="subculture",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.subculture",
                verbose_name="Субкультура",
            ),
        ),
    ]
